pipeline {
    agent any
      stages {
          stage("CreateStack"){
	    steps {
               sh "aws cloudformation update-stack --stack-name CD8 --template-body file://Cloud-Formation-Features/sample2.json   --region 'us-east-1'"
	       }
	    }

}
}


