pipeline {
    agent any
      stages {
          stage("CreateStack"){
	    steps {
               sh "aws cloudformation create-stack --stack-name CD4 --template-body file://Cloud-Formation-Features/sample.json   --region 'us-east-1'"
	       }
	    }

}
}


