pipeline {
    agent any
      stages {
          stage("CreateStack"){
	    steps {
               sh "aws cloudformation create-stack --stack-name CD3 --template-body file://sample.json   --region 'us-east-1'"
	       }
	    }

}
}


